### ISSUE TITLE
catch swiftclient.exceptions.ClientException

### ISSUE THREAD

**Issue by blankdots** [CSCfi/swift-browser-ui#117]
#### Describe the bug

User is shown not authorized if it goes to project not authorized for swift

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to 'project not authorized for openstack swift'
```
ui_1        | [2020-12-01 09:02:54][swiftclient.service][10 MainProcess][ERROR   ] (L:976) _list_account_job: Account GET failed: https://<url>?format=json 401 Unauthorized  [first 60 chars of response] b'{"Code":"AccessDenied","RequestId":"<redacted>'
ui_1        | Traceback (most recent call last):
ui_1        |   File "/usr/local/lib/python3.7/site-packages/swiftclient/service.py", line 951, in _list_account_job
ui_1        |     headers=req_headers
ui_1        |   File "/usr/local/lib/python3.7/site-packages/swiftclient/client.py", line 1859, in get_account
ui_1        |     delimiter=delimiter)
ui_1        |   File "/usr/local/lib/python3.7/site-packages/swiftclient/client.py", line 1802, in _retry
ui_1        |     service_token=self.service_token, **kwargs)
ui_1        |   File "/usr/local/lib/python3.7/site-packages/swiftclient/client.py", line 882, in get_account
ui_1        |     raise ClientException.from_response(resp, 'Account GET failed', body)
ui_1        | swiftclient.exceptions.ClientException: Account GET failed: https://<url>?format=json 401 Unauthorized  [first 60 chars of response] b'{"Code":"AccessDenied","RequestId":"<redacted>'
```
#### Expected behaviour

Show a message that user is not authorized for this project.

Catch exception in other methods as well

**Comment by blankdots** [comment]
difficult to catch that exception, a better idea would be to address the list result `i["success"]` and `i["error"]` in a different function however it does not provide much value, as if that project is enabled for the user but there is no access, containers will still not be accessible.

A better idea will be to filter the project if the user does not have access, but it is also difficult to achieve.

Resuming to extending the empty message to reflect that the project might not be enabled for user to use containers.

**Comment by blankdots** [comment]
closing as won't fix for now as it is not a breaking error
